plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
domain: ajrpugs.github.io/ # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://ajrpugs.github.io # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "/pugsleyfiction"  # place folder name if the site is served in a subfolder